name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  shared_preferences: ^2.0.10
  google_sign_in: ^5.1.0
  math_expressions: ^2.0.0
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true